#!/bin/bash

if [[ -f "$(git pwd)/.git/hooks/post-checkout" ]]; then
  "$(git pwd)/.git/hooks/post-checkout" || exit 1;
fi

if [[ -n "$(git config --local filter.lfs.clean)" ]]; then
  echo "Running Git LFS post-checkout";
  git lfs post-checkout "$@";
fi
