#!/bin/bash

if [[ -f "$(git pwd)/.git/hooks/post-merge" ]]; then
  "$(git pwd)/.git/hooks/post-merge" || exit 1;
fi

if [[ -n "$(git config --local filter.lfs.clean)" ]]; then
  echo "Running Git LFS post-merge";
  git lfs post-merge "$@";
fi
