#!/bin/bash

if [[ -f "$(git pwd)/.git/hooks/pre-commit" ]]; then
  "$(git pwd)/.git/hooks/pre-commit" || exit 1;
fi

git diff --cached | grep -i "^\+ .*NOCOMMIT"
rc=$?

if [[ $rc != 1 ]]; then
  echo ;
  echo 'Trying to commit a "nocommit"-message!';
  echo 'Aborting commit. Remove before committing.';
  echo '(Use `git commit --no-verify` to skip commit hooks)';
  exit 1;
fi

git diff --cached | grep -i "^\+ .*<<<<<<<"
rc=$?

if [[ $rc != 1 ]]; then
  echo ;
  echo 'Trying to commit "<<<<<<<". Probably an unresolved merge conflict.';
  echo 'Aborting commit. Resolve all conflicts before committing.';
  echo '(Use `git commit --no-verify` to skip commit hooks)';
  exit 1;
fi
